//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicis()
        {
            this.Sinavİlan = new HashSet<Sinavİlan>();
        }
    
        public int kullaniciId { get; set; }
        public string eposta { get; set; }
        public string sifre { get; set; }
        public string yetki { get; set; }
        public bool aktiflik { get; set; }
        public string AdSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sinavİlan> Sinavİlan { get; set; }
    }
}
